Repository sanster23/k8s-prow-guide, pull requests merged in 2019-04, with the labels that each got.

#5 update app
  app.py
Labels: size/XS

#6 Feat/f3
  app.py
  config.yaml
  plugins.yaml
  prow_starter.yaml
Labels: size/XL

#11 Feat/f5
  README.md
  app.py
  docker/Dockerfile
  docker/checkout.sh
  docker/entrypoint.sh
  testapp.py
Labels: size/L

#13 update ci entrypoint
  docker/entrypoint.sh
  flask_app_kube.yaml
Labels: size/XS

#14 update ci entrypoint
  docker/entrypoint.sh
Labels: size/M

#15 update ci entrypoint
  docker/entrypoint.sh
Labels: size/XS

#16 update ci entrypoint
  docker/entrypoint.sh
Labels: size/XS

#17 update ci cd with argo and minio
  app.py
  docker/Dockerfile
  docker/entrypoint.sh
  docker_ci_cd/Dockerfile
  docker_ci_cd/checkout.sh
  docker_ci_cd/run_workflows.sh
  helm-charts/flask-app/Chart.yaml
  helm-charts/flask-app/templates/NOTES.txt
  helm-charts/flask-app/templates/flask_app_kube.yaml
  helm-charts/flask-app/values.yaml
  helm-charts/release_workflow/.helmignore
  helm-charts/release_workflow/Chart.yaml
  helm-charts/release_workflow/templates/NOTES.txt
  helm-charts/release_workflow/templates/release_argo_workflow.yaml
  helm-charts/release_workflow/values.yaml
  helm-charts/testing_workflow/.helmignore
  helm-charts/testing_workflow/Chart.yaml
  helm-charts/testing_workflow/templates/NOTES.txt
  helm-charts/testing_workflow/templates/test_argo_workflow.yaml
  helm-charts/testing_workflow/values.yaml
Labels: size/L

#18 update dockerfile and plugins+config prow
  config.yaml
  docker_ci_cd/Dockerfile
  docker_ci_cd/run_workflows.sh
  plugins.yaml
Labels: size/M

#19 adding presets and pod utils
  config.yaml
  docker_ci_cd/Dockerfile
  docker_ci_cd/run_workflows.sh
Labels: size/L

#20 update ci image
  config.yaml
  docker_ci_cd/run_workflows.sh
Labels: size/S

#22 test
  Dockerfile
  config.yaml
Labels: size/S

#23 Update testapp.py
  testapp.py
Labels: size/XS

#25 update ci image
  docker_ci_cd/Dockerfile
  docker_ci_cd/run_workflows.sh
Labels: size/M
